services:
  expo:
    build: .
    container_name: spoweek-tournament-admin
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # mobile Expo
      - "19001:19001" # mobile Expo
      - "19002:19002" # Expo dev tools
      - "19006:19006" # web
    volumes:
      - ./:/app
    environment:
      - API_BASE_URL=http://spoweek-tournament-api-laravel.test-1:80
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    networks:
      - spoweek-network

networks:
  spoweek-network:
    external: true

